### ISSUE TITLE
[BUG] Clicking on items land you on the wrong location after press back

### ISSUE THREAD

**Issue by dkmcgowan** [dwainscheeren/dwains-lovelace-dashboard#109]
If you are on the main page, on rooms section, and click a lock, or vacuum, or something in the header, then click the back button, you will land on devices, not rooms, it doesn't remember where you were before

**Comment by dwainscheeren** [comment]
Will look into this for 1.4.0

**Comment by dwainscheeren** [comment]
Can't fix this for now. If you go into devices and then for example to a vacuum it goes to the room->vacuum. If you click back you are indeed in the room instead of devices. This is because of the lovelace routing, I can't adjust this or I need to make a own card for this but will take a lot of work.
