### ISSUE TITLE
Android dashboard empty

### ISSUE THREAD

**Issue by InanZen** [dwainscheeren/dwains-lovelace-dashboard#345]
When viewing the dashboard from android HA app the dashboard is completely empty, even after server restart, app reload, cleared cache. On the computer (web interface) it displays correctly.
<img src=https://user-images.githubusercontent.com/1391836/146071864-76842237-2156-474e-80bb-746f29eb342e.jpg height="300"/>

**Comment by bulburDE** [comment]
Since I didn't find a confirmation on a fix in android: I had a smiliar problem ( not empty page but an error message as in #344) in the browser and on the app. In the browser on my laptop strg+F5 to clean the cache worked. On android navigating in the android settings to the home assistant app and clearing the app cache did work.

**Comment by InanZen** [comment]
My HA android app has no "clear cache" in the settings (app configuration from HA menu). Unless you mean the android's settings (which as mentioned did not help). Anyway the problem was resolved in v2.0.5. Thanks dwain!
