### ISSUE TITLE
Dashboard doesnt work on the cloud outside my home

### ISSUE THREAD

**Issue by odechr** [dwainscheeren/dwains-lovelace-dashboard#352]
Hi!

This might be a silly problem. But each time i try to load the dashboard when im not home (trough nabu Casa cloud) i get:
"Custom elemtn doesnt exist: dwains-dashboard".

Any reason for that? only when im not local..

**Comment by dwainscheeren** [comment]
Try clearing your cache

**Comment by jasonmhite** [comment]
Resurrecting this because clearing my cache doesn't work. 

Accessing through the nabu casa endpoint, the _first_ time I navigate to DD I get 
![image](https://user-images.githubusercontent.com/868722/165403644-730b9078-91ac-4385-ae5f-ebc3e07d1e75.png)
but then hitting reload and it loads up fine. Close the window and the process repeats. As said I have cleared cache multiple times.

**Comment by Rak3tenmann** [comment]
Exactly the same issue. Nothing helps but uninstalling the mobile app and reinstall.
If there is an easier way, please share.
Maybe a "clear cache" button in the app would be a good idea.
