### ISSUE TITLE
DD kills Lovelace remote access :(

### ISSUE THREAD

**Issue by vincegre** [dwainscheeren/dwains-lovelace-dashboard#442]
Hi

Just installed DD version 2 in my HA, it works fine so far excepted it killed the remote access at HA :( I installed DD following the documentation: first install it in HACS, then add the integration with HA reboot between each steps.
HA is up-to-date (hassio setup). Once done with setup I can't access anymore my HA instance through Nabu Casa URL although HA still states it's properly connected at Nabu Casa. Tried different browsers but exactly the same. In Firefox it gives that error when trying to access nabu casa URL of my instance:

`PR_END_OF_FILE_ERROR`

If I access my HA using local IP address it works fine !

Any idea what's the problem there ? I'd like really to use DD but too problematic for now :(

Thanks, let me know if you need some logs of something or tests done to find out the exact issue !

Vincèn

**Comment by LordNex** [comment]
Sounds like you have an issue with your DNS and SSL Certificate. DD doesnt have anything do with that. I'd suggest instsalling DuckDNS with the LetsEncrypt addon and pick a subdomain off them. Then build your cert around that and the addon will make sure it stays up to date. Of course this is all dependant on your current DNS configuration and build.

**Comment by vincegre** [comment]
> Sounds like you have an issue with your DNS and SSL Certificate. DD doesnt have anything do with that. I'd suggest instsalling DuckDNS with the LetsEncrypt addon and pick a subdomain off them. Then build your cert around that and the addon will make sure it stays up to date. Of course this is all dependant on your current DNS configuration and build.

Sorry but I use nabu casa remote access as stated in my previous message !! will give up on that and find out a better theme ;)

**Comment by rkotulan** [comment]
I use nabu casa remote access with DD 2 without problem.

**Comment by vincegre** [comment]
> I use nabu casa remote access with DD 2 without problem.

Thanks for the feedback but considering poor support and software released only on Discord, I'd better use something else :+1:

**Comment by dwainscheeren** [comment]
Poor support on?

**Comment by jimz011** [comment]
> > I use nabu casa remote access with DD 2 without problem.
> 
> Thanks for the feedback but considering poor support and software released only on Discord, I'd better use something else :+1: 

Poor support? I dont use this project myself, but I can tell you that the support is great. Also your problem has absolutely nothing to do with DD. Not even "remotely" (pun intended).

Lastly why do you say the software is only being released on discord? No it is in HACS, you dont even need to install custom repositories or whatsoever.

If you are referring to DD 3 then yes, because it is a closed BETA. Obviously he doesn't want to make it public yet. As a developer myself this can get me pretty upset. Read first before complaining. Or just dont use the software.

**Comment by LordNex** [comment]
Yes you explained that part which is what helped me narrow it down. I don’t think your DNS is working correctly. Regardless of what desktop you decide on, you really should brush up on DNS and SSL design and configuration. Not saying that to be rude, but as a 20+ year IT vet, I’d bet money on that being where your problem lies.

Benjamin T Powers

On Apr 12, 2022, at 1:22 AM, Vincèn ***@***.***> wrote:

﻿

Sounds like you have an issue with your DNS and SSL Certificate. DD doesnt have anything do with that. I'd suggest instsalling DuckDNS with the LetsEncrypt addon and pick a subdomain off them. Then build your cert around that and the addon will make sure it stays up to date. Of course this is all dependant on your current DNS configuration and build.

Sorry but I use nabu casa remote access as stated in my previous message !! will give up on that and find out a better theme ;)

**Comment by cr-solutions** [comment]
I have the same problem, local IP access to the DD works fine. Over Nebu Casa cloud access I get the following error:

`Custom element doesn't exist: dwains-dashboard-layout. title: Home icon: mdi:home path: home type: custom:dwains-dashboard-layout cards: - type: custom:homepage-card`

@dwainscheeren

Can I support you somehow to analyze this issue?

kind regards
Ricardo
