### ISSUE TITLE
[FR] Use home assistant areas instead of separate rooms.yaml

### ISSUE THREAD

**Issue by patman15** [dwainscheeren/dwains-lovelace-dashboard#53]
As discussed on slack, would be a nice thing to use areas instead of having to create a separate rooms.yaml. I understood that the feature is not yet mature enough to update the theme now. So this is just meant as a reminder for later.

**Comment by dwainscheeren** [comment]
Yes, I answered a same question today on the forum with the following:

> I have already given a lot of thoughts on this, even way back before my theme wasn’t released yet. The problem with using area’s to build/make rooms is that is only contains entities with different domains. I can get the lights, media_players, covers etc out of it that shouldn’t be a problem (but a lot of custom js work), but for example if you got 4 binary_sensor’s places in a area I don’t know which one is a window sensor or a door sensor. Also it gives some universal with HA starters like for example a lot of users of my theme has switches as lights and don’t converted them to a light, so they end up under devices instead of lights. I made an option in my current setup that you can hang a switch inside the lights, but that wouldn’t work then, they first need to convert it to a light and things like that give me a lot of support questions (here, on 2 slack groups and even by email I got a lot of questions).

I’m thinking of changing my theme in the future and I made myself 2 options. 1 option is to go indeed the way of area’s get as much as possible entities out of it so people don’t have to set lights, media_players, vacuums etc for each room, but they still need to define what are door sensors etc.
Or the other option is to add a link in the HA sidebar for Configure Dwains Theme, where you get a complete GUI where you can make rooms with just clicking and adding devices to it, then on the backend it will save those information into the current YAML files and build the theme. That way people can click and drag to build my theme instead of writing YAML files. Maybe I can even make a combination of option 1 and 2. Load all area’s in the GUI but define which entity is what.

But as you may hear this is a lot of work. I already spend more then 20-30 hours minimum a week on this project next to my fulltime job. And I have a lot of work for 1.3.0 now to do. It will include more then 5 new big awesome features.

But regarding your message, yeah I will defintly make my them easier to use in some following updates, as I often say Rome wasn’t built in a day. :slight_smile:

**Comment by jaburges** [comment]
I think Areas is the 'right' way to go, but its a little chicken and egg. Areas wont mature until people start using it more broadly and equally people wont use it until it is more mature :/ 

Pulling the entities from an area will force people to create a good structure within their areas (which are really rooms in this sense).
It will also require people format their sensors correctly with `device_class` - then you can pull the window sensors, the door sensors etc. 

That said, you should potentially ignore everything I have just said as there are always exceptions. Some areas you may not want to have a page for? 
Some areas present complicated decisions for the user - open plan spaces, or apartments. Locks/doors are in a large area, but which `area` gets to have the door/lock (if any)

I think the GUI panel (like the HACS panel) could be the way to go to get more users to be able to use your theme - it is very powerful though!

It would be interesting to 'auto-populate' based on `areas` and then have the user customize their views via the GUI/yaml. 
This all depends on if you are getting enough beer/coffee from those using the theme!?

**Comment by dwainscheeren** [comment]
> It would be interesting to 'auto-populate' based on areas and then have the user customize their views via the GUI/yaml.
I think it will be something this way. Also for persons etc people now add custom addons to them I need to make something that you can still do this.

> This all depends on if you are getting enough beer/coffee from those using the theme!?
Yes haha

**Comment by dwainscheeren** [comment]
This will be possible in DD 3.0.
