### ISSUE TITLE
[FR] Be able to select which sensor gets used for each area

### ISSUE THREAD

**Issue by ToniGnocchi** [dwainscheeren/dwains-lovelace-dashboard#545]
use case: when having more than one temperature/humidity sensor on a room/are., 

current behaviour: right now you get the average temperature. this use case would be use for example to monitore your server room, many of the devides (r.Pi, NAS...) have their own temperature sensors  and some of them might not be relevant for a first glance view.

Expected behaviour: be able to select if you want to display the average of the temperature/humidity sensor on a room or pick the sensor you want to be displayed. In my cases, i have as NAS, R.Pi and a mija termomether to monitor the "server room" and this one is the triger for my fan automation so I would like to be able to pick this entity for the displayed temperature

Many thanks for considering this feature request!

**Comment by Bruskey** [comment]
+1 for me. I have a temperature sensor in my fridge as well as in the general kitchen area, and its showing the temperature of the kitchen area as the average of the ambient temperature as well as the inside fridge temperature.

**Comment by dwainscheeren** [comment]
This is already possible, just exclude the sensors you don't want to use in DD.

**Comment by miljume** [comment]
Excluding isnt a good workaround. Lets say you have a kitchen area where you have temperature sensors in the fridge, the freezer and in the kitchen itself. Then I dont want an average temp between these 3 to show in the dashboard. I also dont want to exclude the sensors in the fridge and freeezer since I am still interested in these values and graphs as well. So I still think selecting default temp sensor is a valid CR

**Comment by dwainscheeren** [comment]
Yeah that is wat exclude does. It just excludes them from the area overview button temp calculation nothing else.

**Comment by miljume** [comment]
Ah my bad, I mixed it up with "Hide" or "Inactivate", thanks for clarifying!
