### ISSUE TITLE
Extremely Slow Loading and Responses Often Freezes

### ISSUE THREAD

**Issue by loca5790** [dwainscheeren/dwains-lovelace-dashboard#663]
Hey Dwain,

Appreciate you first off.  I notice many similar comments. 

I migrated from 2.xx to 3.3.0 and my pages can take 40+ seconds to load.  If I got to the buttons page it often will freeze and I will have to restart the browser from whichever device I am on. Cameras will take literal minutes to load stream where if I got to my overview dashboard they will load in sub 5 seconds for all streams.

To note.  I have not moved over any custom pages (I had about 15) due to this response.  I have removed and hidden any of the entities not in use.  It is thrifted down to relevant items.

I can get any data you like.

It's running on an RPI4 16 GB.

Memory is sitting at 20-24%
Processor 12%
Disk Usage 40% (running on an SSD)

**Comment by ghost** [comment]
To improve performance, I suggest you to remove the sensors that are not used from the area in HA instead of hiding them in the Dwains dashboard.  When we hide or deactivate them, there is an entry added in the entities.yaml file.  This file seems to be a bottleneck and slows down the dashboard.  Once you have removed them from the area in HA, clean up the entities.yaml file

![085A36A0-48A5-447B-95B0-C7ED7C8F93A4](https://user-images.githubusercontent.com/83040228/209415609-c64ac508-92fc-4af8-a633-bf14b2d15526.jpeg)

**Comment by loca5790** [comment]
> To improve performance, I suggest you to remove the sensors that are not used from the area in HA instead of hiding them in the Dwains dashboard.  When we hide or deactivate them, there is an entry added in the entities.yaml file.  This file seems to be a bottleneck and slows down the dashboard.  Once you have removed them from the area in HA, clean up the entities.yaml file
> 
> 
> 
> ![085A36A0-48A5-447B-95B0-C7ED7C8F93A4](https://user-images.githubusercontent.com/83040228/209415609-c64ac508-92fc-4af8-a633-bf14b2d15526.jpeg)
> 
> 


I have 689 lines in that file..... it will take some time to cleanup but that sure makes sense. I'll report back in a couple days.

**Comment by loca5790** [comment]
So far so good, I cleaned that list up by only 60% and everything is extremely responsive.  I'm not sure if the bottleneck is specific to the system it is running on but I have no users logged in and the PI just hosts homeassistant.  All DB's are offloaded as well.   

Appreciate the help @MichelJourdain

**Comment by BernieV1977** [comment]
I'm facing the same problem. My entities.yaml file has +- 3000 entries (79 kb) but I can't clean up nothing totally from the area in HA itself because of it's unusable in DD afterwards. Only the necessary entities from the devices are on the DD dashboard to show.
The dashboard is superslow and almost unusable. Other default pages from HA like Energy are much faster.
