### ISSUE TITLE
No way to paste yaml for new page.

### ISSUE THREAD

**Issue by roja45** [dwainscheeren/dwains-lovelace-dashboard#664]
Trying to create a new page.

More > Create new page > Dwains Dashboard Blueprint 

I have the yaml, but I don't have the area to paste it.

![image](https://user-images.githubusercontent.com/19314911/209589846-31c87deb-79ca-4b26-9959-3c3e6621054e.png)

**Comment by ghost** [comment]
Known issue, see issue https://github.com/dwainscheeren/dwains-dashboard-blueprints/issues/104

**Comment by dwainscheeren** [comment]
This problem is finally patched in v3.4.3 which will be released this weekend. You can now try it as beta https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/v3.4.3
I'm also working on a DD v4.0 which will be complete rewritten from scratch. Sponsoring people will get early access to an stable alpha version asap.  Take a look here to get access: https://github.com/sponsors/dwainscheeren
