### ISSUE TITLE
Cannot add blueprints in 3.4.1

### ISSUE THREAD

**Issue by dannybloe** [dwainscheeren/dwains-lovelace-dashboard#678]
I am trying to add a blueprint and after pasting the yaml code and clicking install it says: no yaml code entered.

**Comment by dannybloe** [comment]
Looks like `_installBlueprintYamlChanged` handler is never called when modifying the yaml code so `_handleInstallBlueprintClicked` fails.

**Comment by thundergreen** [comment]
same here :)

**Comment by MerekW** [comment]
Same issue

**Comment by CaptSonic** [comment]
Is there another way to add the blueprints?

**Comment by thundergreen** [comment]
Are you using beta? It's fixed more or less in beta

CaptSonic ***@***.***> schrieb am Do., 9. März 2023, 10:30:

**Comment by CaptSonic** [comment]
I use the 3.4.1

**Comment by dwainscheeren** [comment]
This problem is finally patched in v3.4.3 which will be released this weekend. You can now try it as beta https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/v3.4.3
I'm also working on a DD v4.0 which will be complete rewritten from scratch. Sponsoring people will get early access to an stable alpha version asap.  Take a look here to get access: https://github.com/sponsors/dwainscheeren

**Comment by thundergreen** [comment]
Will past sponsors also get early access ? I don't know why but it stopped
out of sudden and I never had a look at it why .

Dwain Scheeren ***@***.***> schrieb am Sa., 18. März 2023,
20:05:
