### ISSUE TITLE
Need to re-open: Adding Blueprint - YAML editor does not appear

### ISSUE THREAD

**Issue by Tobster77** [dwainscheeren/dwains-lovelace-dashboard#680]
Following the last discussions in that issue report, it needs to be re-opened:
https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/550

**Comment by maksimkurb** [comment]
I've found a hacky temporary fix for this issue.

You can open/create any automation, add an action and view it in YAML mode (you should see YAML editor).

After this, without reloading the page, go to Dwains Dashboard and try to add new blueprint. You will see YAML editor in popup until you refresh the page.

**Comment by dwainscheeren** [comment]
This problem is finally patched in v3.4.3 which will be released this weekend. You can now try it as beta https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/v3.4.3
I'm also working on a DD v4.0 which will be complete rewritten from scratch. Sponsoring people will get early access to an stable alpha version asap.  Take a look here to get access: https://github.com/sponsors/dwainscheeren
