### ISSUE TITLE
[FR] Method to set Hue/Dim/Colour of all Grouped Lights at once

### ISSUE THREAD

**Issue by konradwalsh** [dwainscheeren/dwains-lovelace-dashboard#7]
Currently a doubled tap on the group card turns on/off the lights in that group.
However, to set the colour, you must tap each individual light and set manually

Ideally, Group Icon might offer two methods.. 
1) all on/off
2) all sett to same...

**Comment by dwainscheeren** [comment]
Good idea. I'm working on it.

**Comment by dwainscheeren** [comment]
I'm looking into this but currently it is not possible to control the color etc of a group of lights. I need to make an own card for it which handles that. You can use this: https://www.home-assistant.io/integrations/light.group/ And then use that entity inside a room light(group). 

However I made the titles of the rooms on the all lights page clickable with a popup and double click to toggle those so you can easy turn on/off all lights of a room on the all lights page.

**Comment by joyka** [comment]
This looks like a nice option to consider https://github.com/bokub/rgb-light-card

**Comment by colin715** [comment]
I would love this feature. I'm using 3 RGBW lights for my front porch, and it's a huge hassle if I want to dim them all or change the color. It's also near impossible to get the same exact color for all three lights.

**Comment by colin715** [comment]
Following up on this, I did notice that if the group of lights is under "More entities" rather than lights, you can change all of them together.  If you could implement something like that for the lights, that would be great.  

An issue with the lights as a more entities option though, is that they won't be counted as a light that is on in the header.  So for instance, I have a nightstand group of lights in the master bedroom.  I don't want them to be part of the light entity because I don't want them automatically turned on when I double-tap the room, I want them only turned on when I go to their group inside of the room and double-tap it.  But I do want them to be counted in the header as a light that is on.  Dwain - this is very related to the original FR, but not the exact same thing.  Do you want me to add a new FR for this?

**Comment by dwainscheeren** [comment]
@colin715 can't you create a group for those 3 lights so it makes it into 1 extra light?
