### ISSUE TITLE
Problems with popup card

### ISSUE THREAD

**Issue by dcantere** [dwainscheeren/dwains-lovelace-dashboard#708]
I'm having problems with pop-up cards. I put that in the settings the entities use the pop-up card itself. I configure it the way it has to be, but the card card does not appear. I've already cleared cache, I've changed browser and nothing. Does anyone have any idea how to resolve?

**Comment by marcusboon** [comment]
+1 for pop ups not working. Configuring individual popups or even trying to replace entire entity types with a pop up blueprint yields the default pop up behaviour regardless of browser or app.

Steps to reproduce:
1. In a dashboard, edit the pop up setting.
2. Pick a Lovelace card (e.g. webrtc-camera card for a camera entity)

Expected:
On click, the camera entity shows the configured webrtc-camera card.

Actual:
On click, the camera entity shows the default entity more info card instead of the configured webrtc-camera card even though reconfiguring the pop up settings for that camera entity shows the correct webrtc-camera config.

Alternatively:
1. Create a webrtc-camera replace card bluprint
2. In the entities dashboard, replace the pop up card with preconfigured webrtc-camera blueprint

Expected:
All camera entities now inherit the webrtc-camera pop up behaviour

Actual:
All camera entities still use the default camera entity more-info behaviour.
